# Generated by Django 4.2 on 2023-04-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county',
            new_name='state',
        ),
    ]
